#############################################################################################
# This role deletes the Vault configurations for each service
#############################################################################################

#############################################################################################
# Delete the Ambassador Creds
- name: Delete Ambassador creds
  k8s:
    kind: Secret
    namespace: default
    name: "{{ service.value['name'] }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    state: absent
  ignore_errors: yes

############################################################################################
# This task deletes vault auth
- name: Delete vault-auth path
  shell: |
    vault delete sys/auth/corda{{ service.value['name'] }}
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"

############################################################################################
# This task deletes crypto materials from vault
- name: Delete Crypto for services
  shell: |
    vault secrets disable {{ service.value['name'] }}
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"

# This task deletes the policies
- name: Delete policy
  shell: |
    vault policy delete vault-crypto-{{ service.value['name'] }}-ro
  environment:
    VAULT_ADDR: "{{ item.vault.url }}"
    VAULT_TOKEN: "{{ item.vault.root_token }}"

# Delete the Ambassador Creds for CA
- name: Delete Ambassador creds
  k8s:
    kind: Secret
    namespace: default
    name: "{{ service.value['name'] }}-ambassador-certs"
    kubeconfig: "{{ kubernetes.config_file }}"
    context: "{{ kubernetes.context }}"
    state: absent
  ignore_errors: yes