kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: baf-dzamba-partner-minikube-storageclass
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  encrypted: "true"
