# This task registers a temporary directory
- name: Register temporary directory
  tempfile:
    state: directory
  register: tmp_directory
  changed_when: false

# This task checks if go is already installed or not
- name: Check go
  stat:
    path: "{{ bin_install_dir }}/go"
  register: go_stat_result
  changed_when: false

- name: Download golang tar 
  get_url:
    url: "https://storage.googleapis.com/golang/go{{ go.version }}.{{ install_os }}-{{ install_arch }}.tar.gz"
    dest: "{{ tmp_directory.path }}"
    mode: 0440
  when: not go_stat_result.stat.exists

- name: Extract the Go tarball
  unarchive:
    src: "{{ tmp_directory.path }}/go{{ go.version }}.{{install_os}}-{{install_arch}}.tar.gz"
    dest: "/usr/local"
    copy: no
  when: not go_stat_result.stat.exists

- name: create bin directory
  file:
    path: "{{ bin_install_dir }}"
    state: directory
  when: not go_stat_result.stat.exists

- name: Copy go binary to destination directory
  copy:
    src: "/usr/local/go/bin/go"
    dest: "{{ bin_install_dir }}/"
    mode: 0755
    remote_src: yes
  when: not go_stat_result.stat.exists

- name: Test go installation
  command: "go version"
  changed_when: false
  tags:
    - molecule-idempotence-notest
