---
dependencies:
  - role: "{{playbook_dir}}/../../shared/configuration/roles/setup/kubectl"
    vars:
      kubectl:
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
  - role: "{{playbook_dir}}/../../shared/configuration/roles/setup/helm"
    vars:
      helm:
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
        checksum: ""

  - role: "{{playbook_dir}}/../../shared/configuration/roles/setup/aws-auth"
    vars:
      aws_authenticator:
        version: "1.10.3"
        release_date:  "2018-07-26"
        os: "{{ install_os }}"
        arch: "{{ install_arch }}"
        bin_directory: "{{ bin_install_dir }}"
        checksum: ""
      kubeconfig_path: "{{ org.k8s.config_file }}"
      kubecontext: "{{ org.k8s.context }}"
    when: "org.cloud_provider == 'aws'"
