---
#######################################
# Playbook to setup the environment for running the Blockchain Automation Framework configurations
#  - checks and installs kubectl, helm and vault clients
#  - If cloud platform is AWS, checks and installs aws-cli and aws-authenticator
#######################################
  - hosts: ansible_provisioners
    gather_facts: yes
    no_log: "{{ no_ansible_log | default(false) }}"
    tasks:
    - include_role:
        name:  setup/kubectl
      vars:
        kubectl:
          version: "1.20.0"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: "sha256:785c1fda09d1d34a94e51b90841faa5ee9f7bf897cb2665426e0ea59f8ddd9e5"
      with_items: "{{ network.organizations }}"
    - include_role:
        name:  setup/helm
      vars:
        helm:
          version: "v3.2.4"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: ""
      with_items: "{{ network.organizations }}"
    - include_role:
        name:  setup/vault
      vars:
        vault:
          version: "1.7.0"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: ""
        with_items: "{{ network.organizations }}"
    - include_role:
        name: setup/aws-cli
      vars:
        aws_cli:
          bin_directory: "{{ bin_install_dir }}"
        aws_access_key: "{{ item.aws.access_key }}"
        aws_secret_key: "{{ item.aws.secret_key }}"
      with_items: "{{ network.organizations }}"
      when: "item.cloud_provider == 'aws' or item.cloud_provider == 'aws-baremetal'"
    - include_role:
        name: setup/aws-auth
      vars:
        aws_authenticator:
          version: "1.10.3"
          release_date:  "2018-07-26"
          os: "{{ install_os }}"
          arch: "{{ install_arch }}"
          bin_directory: "{{ bin_install_dir }}"
          checksum: ""
        kubeconfig_path: "{{ item.k8s.config_file }}"
        kubecontext: "{{ item.k8s.context }}"
      with_items: "{{ network.organizations }}"
      when: "item.cloud_provider == 'aws'"
    vars: #These variables can be overriden from the command line
      privilege_escalate: false           #Default to NOT escalate to root privledges
      install_os: "linux"                 #Default to linux OS
      install_arch:  "amd64"              #Default to amd64 architecture
      bin_install_dir:  "~/bin"           #Default to ~/bin install directory for binaries
